version: '3.0'
services:
  git_clone:
    image: bitnami/git:latest
    working_dir: /temp
    command: >
      bash -c "
        rm -R /nginx/*
        git clone https://github.com/alexh606/AlsWeb2.github.io.git
        cp -R ./AlsWeb2.github.io/. /nginx
      "
    volumes:
      - github:/nginx
  server:
    image: nginx:latest
    restart: always
    depends_on:
      - git_clone
    ports:
      - 9581:80
    volumes:
      - github:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  github: